### ISSUE TITLE
Product Crawl Failed Error

### ISSUE THREAD

**Issue by cghisi** [storyblok/nuxt-storyblok-snipcart#2]
Hi,

I followed the tutorial and implement snipcart in NuxtJS with the V3 but when I want to checkout I have an error (test checkout). I tried different combinations on the snipcart button according to the debug log without success.

_INF > Found 0 snipcart-add-item elements with ids []_

_WRN> An attempt to create an order with invalid products has been made. Don't forget you can't add/update items attributes in the cart dynamically with javascript as it will cause crawling issues._ 

I tried with the V2 and V3 of the snipcart and the problem persists.

```
<b-button
                expanded
                href="#"
                class="snipcart-add-item is-medium"
                :data-item-id="story.content._uid"
                :data-item-name="story.content.title"
                :data-item-description="story.content.simple_description"
                :data-item-price="story.content.price"
                :data-item-quantity="quantity"
                :data-item-url="`https://nuxtjssnipcart.now.sh${currentUrl}`"
                :data-item-image="story.content.images[0].filename"
              >SHOP NOW</b-button>
```

Thanks

**Comment by DominikAngerer** [comment]
That sounds a lot like a problem with Snipcart itself - rather than the implementation in Nuxt our the API of Storyblok. I would recommend asking the Snipcart support for potential solutions.
